filebeat.modules:
- module: netflow
  log:
    enabled: true
    var:
      netflow_host: 0.0.0.0
      netflow_port: 2055

#setup.ilm.rollover_alias: netflow-%{[agent.version]}
#change default index 'filebeat-%{[agent.version]}'
#https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html

output.elasticsearch.index: "netflow-%{[agent.version]}"
setup.template.name: "netflow"
setup.template.pattern: "netflow-%{[agent.version]}"

output.elasticsearch:
  hosts: ["elastic:9200"]
