services:
  www:
    container_name: ${COMPOSE_PROJECT_NAME}_www
    hostname: www
    networks:
      - servers
    build:
      context: ./app/www
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g
  files:
    container_name: ${COMPOSE_PROJECT_NAME}_files
    hostname: files
    networks:
      - servers
    build:
      context: ./app/files
    volumes:
      - $FILES_DATA_DIR:/var/www/html
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g
  test_www:
    container_name: ${COMPOSE_PROJECT_NAME}_test_www
    hostname: test_www
    networks:
      - servers
    build:
      context: ./app/test_www
    volumes:
      - $TEST_WWW_CONFIG_DIR:/usr/share/nginx/html:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g